name: Branch build
on:
  push:
    branches:
      - '*'
      - '!master'

  workflow_dispatch:
    inputs:
      publish_container:
        description: 'Publish container'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Build container
        run:  |
            make image.build

      - name: Set up QEMU
        if: github.event.inputs.publish_container == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: github.event.inputs.publish_container == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        if: github.event.inputs.publish_container == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish versioned container to ghcr.io
        if: github.event.inputs.publish_container == 'true'
        run:  |
          make publish=true registry=ghcr.io/exposr image.xbuild