name: ci
on:
  push:
    branches:
      - '*'
      - '!master'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Build container
        run:  |
            make image.build
